[project]
name = "advent-of-code-25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.9.3",
    "networks",
    "networkx>=3.4.2",
    "pandas>=2.2.3",
]

[tool.ruff]
select = ["ALL"]
